name: dog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # google
  geocoding:
  google_maps_flutter:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:

  # google firebase
  firebase_messaging: ^15.1.2

  # sensor
  geolocator:

  # ui
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.3
  skeletonizer: ^1.3.0
  toastification: ^2.0.0
  animated_toggle_switch: ^0.8.2
  cached_network_image: ^3.3.1

  #networking
  http: ^1.1.2
  http_parser: ^4.0.0

  # etc
  url_launcher:
  flutter_riverpod: ^2.5.1
  permission_handler:
  device_info_plus:
  sqflite: ^2.3.3+1
  transition: ^2.0.2
  table_calendar: ^3.1.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  app_links: ^6.1.4
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3
  flutter_config: ^2.0.2
  stomp_dart_client: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  #image_path_android: "assets/icon/an_symbol.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  #adaptive_icon_background: "#ff663399"
  #adaptive_icon_foreground: "assets/icon/an_symbol.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
        - asset: assets/fonts/Pretendard-Light.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Thin.ttf
        - asset: assets/fonts/PretendardVariable.ttf

# flutter pub run flutter_native_splash:remove
# flutter pub run flutter_native_splash:create
#flutter_native_splash:
#  color: "#41E596"
#  image: assets/images/puppy_1.png
#
#  android_12:
#    image: assets/images/puppy_1_green.png
#
#  android: true
#  ios: true
#  web: false